name: Build iOS

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  framework:
    name: Build Framework Scheme
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['generic/platform=iOS Simulator',
           'generic/platform=iOS']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Framework
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
  example:
    name: Build Example Scheme
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['generic/platform=iOS Simulator',
           'generic/platform=iOS']
    needs: framework
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Example
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: iOS Example
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
