name: Build macOS

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  framework:
    name: Build Framework Scheme
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['generic/platform=macOS']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Framework
        env:
          scheme: RxNetworkKit
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
  example:
    name: Build Example Scheme
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['generic/platform=macOS']
    needs: framework
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Example
        env:
          scheme: macOS Example
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}

