name: Build iOS

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['generic/platform=iOS Simulator',
           'generic/platform=iOS']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Framework
        env:
          scheme: RxNetworkKit
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -scheme '${scheme}' -destination '${destination}' | xcpretty && exit ${PIPESTATUS[0]}
      - name: Build Example
        env:
          scheme: iOS Example
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -scheme '${scheme}' -destination '${destination}' | xcpretty && exit ${PIPESTATUS[0]}
