name: Build

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-ios:
    name: Build For iOS
    uses: ./.github/workflows/build-ios.yml
        
  build-macos:
    name: Build For macOS
    uses: ./.github/workflows/build-macos.yml
    
  build-deploy-docs:
    name: Build and Deploy Docs
    uses: ./.github/workflows/build-deploy-docs.yml
