name: Build and Deploy Docs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-docs:
    name: Build and Deploy Docs
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Docs
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
        run: |
          xcodebuild docbuild -workspace "${workspace}" -scheme "${scheme}" -derivedDataPath derivedData | xcpretty
          mkdir docArchives
          cp -R `find derivedData -type d -name "*.doccarchive"` docArchives
          zip -r RxNetworkKitDocCArchive.zip docArchives/RxNetworkKit.doccarchive
      - name: Upload Doc Archive
        uses: actions/upload-artifact@v3
        with:
          name: doc-archive-zip
          path: RxNetworkKitDocCArchive.zip
          
  deploy:
    runs-on: macos-13
    needs: build-deploy-docs
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Derived Data
        uses: actions/download-artifact@v3
        with:
          name: doc-archive-zip
      - name: Perpare Docs for Deployment
        run: |
          unzip RxNetworkKitDocCArchive.zip
          $(xcrun --find docc) process-archive transform-for-static-hosting RxNetworkKit.doccarchive --hosting-base-path RxNetworkKit --output-path docs
          echo "<script>window.location.href += \"/documentation/rxnetworkkit\"</script>" > docs/index.html;
      - name: Upload Docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy Docs artifact
        id: deployment
        uses: actions/deploy-pages@v1
