name: Build

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  build-ios:
    name: Build For iOS
    runs-on: macos-13

    steps:
      - name: Build iOS
        uses: ./.github/workflows/build-ios.yml
        
  build-macos:
    name: Build For macOS
    runs-on: macos-13

    steps:
      - name: Build macOS
        uses: ./.github/workflows/build-macos.yml
