name: Build and Deploy Docs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-docs:
    name: Build and Deploy Docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Docs
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
        run: |
          xcodebuild docbuild -workspace "${workspace}" -scheme "${scheme}" -derivedDataPath derivedData | xcpretty
      - name: Perpare Docs for Deployment
        run: |
          mkdir docArchives
          cp -R `find derivedData -type d -name "*.doccarchive"` docArchives
          $(xcrun --find docc) process-archive transform-for-static-hosting docArchives/RxNetworkKit.doccarchive --hosting-base-path RxNetworkKit --output-path docs
      - name: Upload Docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'
      - name: Deploy Docs artifact
        id: deployment
        uses: actions/deploy-pages@v1
