name: Build iOS

on:
  workflow_call:
  
jobs:

  framework-ios-simulator:
    name: Build Framework For iOS Simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Framework
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
          destination: generic/platform=iOS Simulator
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
          
  framework-ios:
    name: Build Framework For iOS Device
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Framework
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
          destination: generic/platform=iOS
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}"
          
  example-ios-simulator:
    name: Build Example For iOS Simulator
    runs-on: macos-13
    needs: framework-ios-simulator
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Example
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: iOS Example
          destination: generic/platform=iOS Simulator
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
          
  example-ios:
    name: Build Example For iOS Device
    runs-on: macos-13
    needs: framework-ios
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.0'
      - name: Build Example
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: iOS Example
          destination: generic/platform=iOS
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
