name: Build macOS

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  framework-macos:
    name: Build Framework For macOS
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Framework
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: RxNetworkKit
          destination: generic/platform=macOS
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" | xcpretty && exit ${PIPESTATUS[0]}
          
  example-macos:
    name: Build Example For macOS
    runs-on: macos-13
    needs: framework-macos
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Build Example
        env:
          workspace: RxNetworkKit.xcworkspace
          scheme: macOS Example
          destination: generic/platform=macOS
        run: |
          xcodebuild clean build -workspace "${workspace}" -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}

