name: Build iOS

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-13-x3
    strategy:
        matrix:
          destination: ['generic/platform=iOS Simulator',
           'generic/platform=iOS',
           'generic/platform=macOS']

    steps:
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
          destination: ${{ matrix.destination }}
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          xcodebuild clean build analyze -scheme "$scheme" -destination "${destination}" -"$filetype_parameter" "$file_to_build" | xcpretty && exit ${PIPESTATUS[0]}
