name: Publish Podspec

on:
  push:
    branches:
        - '**'

jobs:
  publish-podspec:
    name: Push Podpsec File To Trunk
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'
      - name: Install Cocoapods
        run: |
          sudo gem install cocoapods
      - name: Trunk Push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push
