name: Swift Package Manager Lint

on:
  workflow_run:
    workflows:
        - 'Build'
    types:
        - completed
    branches:
        - '**'

jobs:
  spm-lint:
    name: Lint Package For Swift Package Manager
    runs-on: macos-13
    strategy:
      matrix:
        destination: ['generic/platform=iOS Simulator',
         'generic/platform=iOS',
         'generic/platform=macOS']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: $
      - run: git branch
      - run: env
      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Update Packages
        run: |
          swift package update
      - name: Build Project
        env:
          project: ./.github/workflows/SPMDummy/SPMDummy.xcodeproj
          scheme: SPMDummy
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -project "${project}" -scheme "${scheme}" -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
          
